import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
    appendTransactionMessageInstructions,
    createTransactionMessage,
    generateKeyPairSigner,
    pipe,
    setTransactionMessageFeePayerSigner,
    setTransactionMessageLifetimeUsingBlockhash,
} from '@solana/kit';
import {
    findAssociatedTokenPda,
    getFreezeAccountInstruction,
    getThawAccountInstruction,
    TOKEN_2022_PROGRAM_ADDRESS,
} from '@solana-program/token-2022';
import { Token } from '../../issuance';
import { createMintToTransaction } from '../../management';
import { createTransferTransaction } from '../../transfer';
import {
    fetchConfirmedTransactionSnapshot,
    fetchOnChainTransaction,
    sendAndPollConfirm,
    setupChainSuite,
    type ConfirmedTransactionSnapshot,
    type OnChainTransaction,
} from './chain-helpers';
import { DEFAULT_TIMEOUT } from './helpers';
import type { FullTransaction } from '../../transaction-util';

// This test only runs when REGENERATE_FIXTURES=true. It builds a representative
// set of transactions, lands them on a local cluster, fetches them back as wire
// bytes, and writes the result to:
//   src/inspection/__tests__/__fixtures__/onchain-transactions.ts
// The unit tests in src/inspection/__tests__/parse-transaction-onchain.test.ts
// then consume those static fixtures without needing chain access.

const SHOULD_RUN = process.env.REGENERATE_FIXTURES === 'true';
const maybeDescribe = SHOULD_RUN ? describe : describe.skip;

interface NamedFixture {
    key: string;
    description: string;
    base64: string;
}

function emit(fixtures: NamedFixture[]): string {
    const lines: string[] = [];
    lines.push('// Generated by src/__tests__/integration/capture-fixtures.test.ts.');
    lines.push('// Re-run via REGENERATE_FIXTURES=true to refresh.');
    lines.push('// Real on-chain wire bytes captured from a local Solana cluster, stored as');
    lines.push('// base64 so unit tests can exercise parseTokenTransaction without a validator.');
    lines.push('');
    lines.push('export interface OnChainFixture {');
    lines.push('    description: string;');
    lines.push('    base64: string;');
    lines.push('}');
    lines.push('');
    lines.push('export const ONCHAIN_FIXTURES = {');
    for (const f of fixtures) {
        lines.push(`    ${f.key}: {`);
        lines.push(`        description: ${JSON.stringify(f.description)},`);
        lines.push(`        base64: ${JSON.stringify(f.base64)},`);
        lines.push('    },');
    }
    lines.push('} as const satisfies Record<string, OnChainFixture>;');
    lines.push('');
    return lines.join('\n');
}

const captured = (key: string, description: string, t: OnChainTransaction): NamedFixture => ({
    key,
    description,
    base64: t.base64,
});

interface ConfirmedNamedFixture {
    key: string;
    description: string;
    snapshot: ConfirmedTransactionSnapshot;
}

function emitConfirmed(fixtures: ConfirmedNamedFixture[]): string {
    const lines: string[] = [];
    lines.push('// Generated by src/__tests__/integration/capture-fixtures.test.ts.');
    lines.push('// Re-run via REGENERATE_FIXTURES=true to refresh.');
    lines.push('// Real confirmed-transaction snapshots from a local Solana cluster, with');
    lines.push('// outer wire bytes plus meta.innerInstructions and meta.loadedAddresses,');
    lines.push('// so parseConfirmedTransaction unit tests can exercise CPI parsing.');
    lines.push('');
    lines.push('export interface OnChainConfirmedFixture {');
    lines.push('    description: string;');
    lines.push('    base64: string;');
    lines.push('    innerInstructions: Array<{');
    lines.push('        index: number;');
    lines.push('        instructions: Array<{');
    lines.push('            programIdIndex: number;');
    lines.push('            accounts: number[];');
    lines.push('            data: string;');
    lines.push('            stackHeight?: number | null;');
    lines.push('        }>;');
    lines.push('    }>;');
    lines.push('    loadedAddresses: { writable: string[]; readonly: string[] } | null;');
    lines.push('}');
    lines.push('');
    lines.push('export const ONCHAIN_CONFIRMED_FIXTURES = {');
    for (const f of fixtures) {
        lines.push(`    ${f.key}: {`);
        lines.push(`        description: ${JSON.stringify(f.description)},`);
        lines.push(`        base64: ${JSON.stringify(f.snapshot.base64)},`);
        lines.push(
            `        innerInstructions: ${JSON.stringify(f.snapshot.innerInstructions, null, 12)
                .replace(/\n {12}/g, '\n        ')
                .replace(/\n {0}\]/, '\n        ]')},`,
        );
        lines.push(
            `        loadedAddresses: ${
                f.snapshot.loadedAddresses ? JSON.stringify(f.snapshot.loadedAddresses) : 'null'
            },`,
        );
        lines.push('    },');
    }
    lines.push('} as const satisfies Record<string, OnChainConfirmedFixture>;');
    lines.push('');
    return lines.join('\n');
}

maybeDescribe('capture parse-transaction fixtures', () => {
    it(
        'writes onchain-transactions.ts',
        async () => {
            const { client, payer, mintAuthority, freezeAuthority } = await setupChainSuite();

            // 1) Issue a basic mint with metadata.
            const mint = await generateKeyPairSigner();
            const issuanceTx = await new Token()
                .withMetadata({
                    mintAddress: mint.address,
                    authority: mintAuthority.address,
                    metadata: { name: 'Fixture Token', symbol: 'FIX', uri: 'https://example.com/fix.json' },
                    additionalMetadata: new Map(),
                })
                .buildTransaction({
                    rpc: client.rpc,
                    decimals: 6,
                    mintAuthority,
                    freezeAuthority: freezeAuthority.address,
                    mint,
                    feePayer: payer,
                });
            const issuance = await fetchOnChainTransaction(client, await sendAndPollConfirm(client.rpc, issuanceTx));

            // 2) Mint to a fresh recipient (idempotent ATA + MintTo).
            const recipient = await generateKeyPairSigner();
            const mintToTx = await createMintToTransaction(
                client.rpc,
                mint.address,
                recipient.address,
                5,
                mintAuthority,
                payer,
            );
            const mintTo = await fetchOnChainTransaction(client, await sendAndPollConfirm(client.rpc, mintToTx));

            // 3) Mint to mintAuthority so they have something to transfer.
            const mintToSelfTx = await createMintToTransaction(
                client.rpc,
                mint.address,
                mintAuthority.address,
                10,
                mintAuthority,
                payer,
            );
            await sendAndPollConfirm(client.rpc, mintToSelfTx);

            // 4) Plain TransferChecked.
            const transferTx = await createTransferTransaction({
                rpc: client.rpc,
                mint: mint.address,
                from: mintAuthority.address,
                to: recipient.address,
                feePayer: payer,
                authority: mintAuthority,
                amount: '1',
            });
            const transfer = await fetchOnChainTransaction(client, await sendAndPollConfirm(client.rpc, transferTx));

            // 5) Multi-instruction admin: Freeze + Thaw on the recipient's ATA in one tx.
            const [recipientAta] = await findAssociatedTokenPda({
                owner: recipient.address,
                tokenProgram: TOKEN_2022_PROGRAM_ADDRESS,
                mint: mint.address,
            });
            const { value: blockhash } = await client.rpc.getLatestBlockhash().send();
            const multiTx = pipe(
                createTransactionMessage({ version: 0 }),
                m => setTransactionMessageFeePayerSigner(payer, m),
                m => setTransactionMessageLifetimeUsingBlockhash(blockhash, m),
                m =>
                    appendTransactionMessageInstructions(
                        [
                            getFreezeAccountInstruction({
                                account: recipientAta,
                                mint: mint.address,
                                owner: freezeAuthority,
                            }),
                            getThawAccountInstruction({
                                account: recipientAta,
                                mint: mint.address,
                                owner: freezeAuthority,
                            }),
                        ],
                        m,
                    ),
            ) as FullTransaction;
            const multi = await fetchOnChainTransaction(client, await sendAndPollConfirm(client.rpc, multiTx));

            const fixtures: NamedFixture[] = [
                captured(
                    'issuanceWithMetadata',
                    'mint creation: CreateAccount + InitializeMint2 + MetadataPointer + InitializeTokenMetadata',
                    issuance,
                ),
                captured('mintTo', 'idempotent ATA create + MintTo to a fresh recipient', mintTo),
                captured('transferChecked', 'TransferChecked from one ATA to another', transfer),
                captured('freezeThawMulti', 'single tx with FreezeAccount followed by ThawAccount', multi),
            ];

            const out = emit(fixtures);
            const target = join(
                __dirname,
                '..',
                '..',
                'inspection',
                '__tests__',
                '__fixtures__',
                'onchain-transactions.ts',
            );
            writeFileSync(target, out);
            // eslint-disable-next-line no-console
            console.log(`Wrote ${fixtures.length} fixtures to ${target}`);

            // Also capture full confirmed-transaction snapshots (with inner
            // instructions and loadedAddresses) for parseConfirmedTransaction tests.
            // mintTo and transfer both invoke the Token-2022 program from the ATA
            // program, so they have meaningful CPIs in meta.innerInstructions.
            const mintToSnap = await fetchConfirmedTransactionSnapshot(client, mintTo.signature);
            const transferSnap = await fetchConfirmedTransactionSnapshot(client, transfer.signature);
            const confirmed = emitConfirmed([
                {
                    key: 'mintToConfirmed',
                    description: 'idempotent ATA create + MintTo, including inner CPIs from ATA program',
                    snapshot: mintToSnap,
                },
                {
                    key: 'transferCheckedConfirmed',
                    description: 'TransferChecked, captured with inner CPIs from execution',
                    snapshot: transferSnap,
                },
            ]);
            const confirmedTarget = join(
                __dirname,
                '..',
                '..',
                'inspection',
                '__tests__',
                '__fixtures__',
                'onchain-confirmed-transactions.ts',
            );
            writeFileSync(confirmedTarget, confirmed);
            // eslint-disable-next-line no-console
            console.log(`Wrote 2 confirmed-tx snapshots to ${confirmedTarget}`);
        },
        DEFAULT_TIMEOUT,
    );
});

if (!SHOULD_RUN) {
    // Keep jest from emitting "your test suite must contain at least one test" when skipped
    // because we used describe.skip. (No-op assertion suite.)
    describe('capture parse-transaction fixtures (skipped)', () => {
        it('skipped (set REGENERATE_FIXTURES=true to run)', () => {
            expect(true).toBe(true);
        });
    });
}
