// Generated by src/__tests__/integration/capture-fixtures.test.ts.
// Re-run via REGENERATE_FIXTURES=true to refresh.
// Real on-chain wire bytes captured from a local Solana cluster, stored as
// base64 so unit tests can exercise parseTokenTransaction without a validator.

export interface OnChainFixture {
    description: string;
    base64: string;
}

export const ONCHAIN_FIXTURES = {
    issuanceWithMetadata: {
        description: 'mint creation: CreateAccount + InitializeMint2 + MetadataPointer + InitializeTokenMetadata',
        base64: 'AykDiA7ILPsBJ+1db1Gl7lZV3gXWs9/YHdowJ/thi9FuE9fTI5GRBLWJWNH7vdEnzU2UW8qlzLA7EBi+MPM6KgQZ3PVrpSjq6RKdeEcHp+BEYsSJ1uznt/aONyGqqlVgqPJCVWnYQxmlnAS38Ru/v85Tq5pjau61roQvba0kwa0K6ivJdpnhONChIau9Yu4it91EW62rL27TQYszh/BcS0KEOWlvi+g3dPMy6s/luZZnpxPhlYeYvJimaRrPKc++CYADAQMGQmkePE0g2fIyVjIrosKe15qc4pP5IWFOrXKoOMd8h6jqEBjzQwGVVCM+F0pvShJMNh/OMRLAfl2c8dX13nvXvBEXtzLrSnm7g7yTf+hKAcooKuEhBeF5b0kt8OVv31A3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAAbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8BoaFnTjICpchSBhBaRfgv4/KFX5GT5jM/Q/6ndPYvP8EAwIAATQAAAAA4Ak0AAAAAADqAAAAAAAAAAbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8BQEBQicAERe3MutKebuDvJN/6EoByigq4SEF4XlvSS3w5W/fUDfqEBjzQwGVVCM+F0pvShJMNh/OMRLAfl2c8dX13nvXvAUCAQRDAAYRF7cy60p5u4O8k3/oSgHKKCrhIQXheW9JLfDlb99QNwEd2Bm/ejrHUTA6eSrz3AXkTSuIhNbnRgppdXRamd9scAUEAQIBAkDS4R6iWLhNjQ0AAABGaXh0dXJlIFRva2VuAwAAAEZJWBwAAABodHRwczovL2V4YW1wbGUuY29tL2ZpeC5qc29uAA==',
    },
    mintTo: {
        description: 'idempotent ATA create + MintTo to a fresh recipient',
        base64: 'AjoyuLYXoNiv7RK+loHJdgVgYre++uDKalMInb9TyuvRlXfJJFzIu76GbNV2xYQuZgHM1wTrj6NYafp/SEpbogGqQ7rXLeg4Gh9CcFkCEpaT4V4tL99Lgf8t0Dp6a/+ghEOz8vi1Cd2Mq5EIDL9Y67wtFg9wObocuF59omoWJqYBgAIBBAhCaR48TSDZ8jJWMiuiwp7Xmpzik/khYU6tcqg4x3yHqBEXtzLrSnm7g7yTf+hKAcooKuEhBeF5b0kt8OVv31A3T0Dq+S6vApWeNhFHDP4vgfNSVKMkQREcUaNGo3TSfkXqEBjzQwGVVCM+F0pvShJMNh/OMRLAfl2c8dX13nvXvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+FmW6LQwpoNo7/R96IUyt2BAH+n1ccZk5TulzRgSwirxSwbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8BoaFnTjICpchSBhBaRfgv4/KFX5GT5jM/Q/6ndPYvQECBQYAAgYDBAcBAQcDAwIBCQdAS0wAAAAAAAA=',
    },
    transferChecked: {
        description: 'TransferChecked from one ATA to another',
        base64: 'Aj4FsrUsWnP5UnaHqgQ9EQoukQCt+5ObrZwctzLUi+IuRnB11ixCGXDwGEh/W29HJlxHo58W4rxtqEY9Rg2PXglCRQgCffmOvy4hRjMijHeEfm9jjcyQOuqRUW3sYr2o+wpMbiKBEi8WFA1jFrycrKwPCS/IzecdkVZueJzl8UcNgAIBAgZCaR48TSDZ8jJWMiuiwp7Xmpzik/khYU6tcqg4x3yHqBEXtzLrSnm7g7yTf+hKAcooKuEhBeF5b0kt8OVv31A3T0Dq+S6vApWeNhFHDP4vgfNSVKMkQREcUaNGo3TSfkWpgg6xqOXa3TTIEtLBMrRbwdHahtHnLWdQ9y0k/5cWfuoQGPNDAZVUIz4XSm9KEkw2H84xEsB+XZzx1fXee9e8Bt324e51j94YQl285GzN2rYa/E2DuQ0n/r35KNihi/wGhoWdOMgKlyFIGEFpF+C/j8oVfkZPmMz9D/qd09i9AwEFBAMEAgEKDEBCDwAAAAAABgA=',
    },
    freezeThawMulti: {
        description: 'single tx with FreezeAccount followed by ThawAccount',
        base64: 'AgkbK/q5n9XBWa98KvqjFz75n9YPmla0EbHrpzP7g9J367VNKBXC3tf7HxlyYj+nmGJClwGv86z2e3YJ30rc0AO44kO/EqSmZ+dfk1A7hXzt279h9HlH3/Y0oK6nqLZ4VjeedFvG+VoLdWkpQxqXoTxZ4R3wsJCvPuCA3dzzNSwFgAIBAgVCaR48TSDZ8jJWMiuiwp7Xmpzik/khYU6tcqg4x3yHqB3YGb96OsdRMDp5KvPcBeRNK4iE1udGCml1dFqZ32xwT0Dq+S6vApWeNhFHDP4vgfNSVKMkQREcUaNGo3TSfkXqEBjzQwGVVCM+F0pvShJMNh/OMRLAfl2c8dX13nvXvAbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8BoaFnTjICpchSBhBaRfgv4/KFX5GT5jM/Q/6ndPYvQQCBAMCAwEBCgQDAgMBAQsA',
    },
} as const satisfies Record<string, OnChainFixture>;
