// Generated by src/__tests__/integration/capture-fixtures.test.ts.
// Re-run via REGENERATE_FIXTURES=true to refresh.
// Real confirmed-transaction snapshots from a local Solana cluster, with
// outer wire bytes plus meta.innerInstructions and meta.loadedAddresses,
// so parseConfirmedTransaction unit tests can exercise CPI parsing.

export interface OnChainConfirmedFixture {
    description: string;
    base64: string;
    innerInstructions: Array<{
        index: number;
        instructions: Array<{
            programIdIndex: number;
            accounts: number[];
            data: string;
            stackHeight?: number | null;
        }>;
    }>;
    loadedAddresses: { writable: string[]; readonly: string[] } | null;
}

export const ONCHAIN_CONFIRMED_FIXTURES = {
    mintToConfirmed: {
        description: 'idempotent ATA create + MintTo, including inner CPIs from ATA program',
        base64: 'AjoyuLYXoNiv7RK+loHJdgVgYre++uDKalMInb9TyuvRlXfJJFzIu76GbNV2xYQuZgHM1wTrj6NYafp/SEpbogGqQ7rXLeg4Gh9CcFkCEpaT4V4tL99Lgf8t0Dp6a/+ghEOz8vi1Cd2Mq5EIDL9Y67wtFg9wObocuF59omoWJqYBgAIBBAhCaR48TSDZ8jJWMiuiwp7Xmpzik/khYU6tcqg4x3yHqBEXtzLrSnm7g7yTf+hKAcooKuEhBeF5b0kt8OVv31A3T0Dq+S6vApWeNhFHDP4vgfNSVKMkQREcUaNGo3TSfkXqEBjzQwGVVCM+F0pvShJMNh/OMRLAfl2c8dX13nvXvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+FmW6LQwpoNo7/R96IUyt2BAH+n1ccZk5TulzRgSwirxSwbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8BoaFnTjICpchSBhBaRfgv4/KFX5GT5jM/Q/6ndPYvQECBQYAAgYDBAcBAQcDAwIBCQdAS0wAAAAAAAA=',
        innerInstructions: [
            {
                index: 0,
                instructions: [
                    {
                        programIdIndex: 7,
                        accounts: [3],
                        data: '84eT',
                        stackHeight: 2,
                    },
                    {
                        programIdIndex: 4,
                        accounts: [0, 2],
                        data: '11119ExAoTptm6xKUTUcw2V69MKmyEdDmRins3j3bK43o9nHeiYUtSiaT9pc292PhNQvxj',
                        stackHeight: 2,
                    },
                    {
                        programIdIndex: 7,
                        accounts: [2],
                        data: 'P',
                        stackHeight: 2,
                    },
                    {
                        programIdIndex: 7,
                        accounts: [2, 3],
                        data: '6XHndZm4YXdJifo2z7dnD9eH8adeyQLUDYwciLHr9eSBU',
                        stackHeight: 2,
                    },
                ],
            },
        ],
        loadedAddresses: { writable: [], readonly: [] },
    },
    transferCheckedConfirmed: {
        description: 'TransferChecked, captured with inner CPIs from execution',
        base64: 'Aj4FsrUsWnP5UnaHqgQ9EQoukQCt+5ObrZwctzLUi+IuRnB11ixCGXDwGEh/W29HJlxHo58W4rxtqEY9Rg2PXglCRQgCffmOvy4hRjMijHeEfm9jjcyQOuqRUW3sYr2o+wpMbiKBEi8WFA1jFrycrKwPCS/IzecdkVZueJzl8UcNgAIBAgZCaR48TSDZ8jJWMiuiwp7Xmpzik/khYU6tcqg4x3yHqBEXtzLrSnm7g7yTf+hKAcooKuEhBeF5b0kt8OVv31A3T0Dq+S6vApWeNhFHDP4vgfNSVKMkQREcUaNGo3TSfkWpgg6xqOXa3TTIEtLBMrRbwdHahtHnLWdQ9y0k/5cWfuoQGPNDAZVUIz4XSm9KEkw2H84xEsB+XZzx1fXee9e8Bt324e51j94YQl285GzN2rYa/E2DuQ0n/r35KNihi/wGhoWdOMgKlyFIGEFpF+C/j8oVfkZPmMz9D/qd09i9AwEFBAMEAgEKDEBCDwAAAAAABgA=',
        innerInstructions: [],
        loadedAddresses: { writable: [], readonly: [] },
    },
} as const satisfies Record<string, OnChainConfirmedFixture>;
